- name: Deploying Petclinic
  hosts: all

  tasks:
    - name: Acquire the executable jar file
      copy: 
          src: /var/lib/jenkins/workspace/spring-petclinic_main/spring-petclinic-2.4.2.jar
          dest: /home/vagrant
    - name: Execute the Petclinic jar file on port 8081
      shell: java -jar -Dserver.port=8081 spring-petclinic-2.4.2.jar