- name: Deploying Petclinic2
  hosts: all

  tasks:
    - name: adwa
      shell: cd /home/vagrant/spring-petclini
    - name: Executing Petclinic jar file
      shell: java -jar spring-petclinic-2.4.2.jar